[otel_agents]
otel_agents ansible_host=34.122.7.201 node_type=collector otel_base_dir=/opt/otel/collector

[otel_gateways]
gateway1 ansible_host=136.116.164.60 node_type=gateway otel_base_dir=/opt/otelAgent-gateway-Observability

[prom_agents]
prom_agent2 ansible_host=136.116.164.60 node_type=prometheus_collector prom_base_dir=/opt/prometheus

[grafana_agents]
grafana_agent2 ansible_host=136.116.164.60 node_type=grafana grafana_base_dir=/opt/grafana

[splunk_agents]
splunk_agent2 ansible_host=136.116.164.60 node_type=splunk splunk_base_dir=/opt/splunk

[node_exporter_agents]
node_exporter_agent2 ansible_host=34.61.4.52 node_type=node_exporter node_exporter_base_dir=/opt/node-exporter

[exporters_agents]
exporters_agent2 ansible_host=34.61.4.52 node_type=exporters exporters_base_dir=/opt/exporters

[docker_host]
docker1 ansible_host=136.116.164.60 node_type=docker
docker2 ansible_host=34.122.7.201 node_type=docker

[all:vars]
ansible_user=singhm
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3

