[otel_agents]
otel_agents ansible_host=35.225.142.255 node_type=collector otel_base_dir=/opt/otel/collector

[otel_gateways]
gateway1 ansible_host=136.64.205.48 node_type=gateway otel_base_dir=/opt/otel/gateway

[prom_agents]
prom_agent2 ansible_host=136.64.205.48 node_type=prometheus_collector prom_base_dir=/opt/prometheus

[grafana_agents]
grafana_agent2 ansible_host=136.64.205.48 node_type=grafana grafana_base_dir=/opt/grafana

[splunk_agents]
splunk_agent2 ansible_host=136.64.191.228 node_type=splunk splunk_base_dir=/opt/splunk

[node_exporter_agents]
node_exporter_agent2 ansible_host=136.64.191.228 node_type=node_exporter node_exporter_base_dir=/opt/node-exporter

[exporters_agents]
exporters_agent2 ansible_host=136.64.191.228 node_type=exporters exporters_base_dir=/opt/exporters

[docker_host]
docker1 ansible_host=35.225.142.255 node_type=docker
docker2 ansible_host=136.64.205.48 node_type=docker

[otel_demo_app]
otel_demo_app ansible_host=35.225.142.255 node_type=otel_demo_app otel_demo_app_base_dir=/opt/otel-demo-app

[otel_demo_app2]
otel_demo_app2 ansible_host=35.225.142.255 node_type=otel_demo_app2 otel_demo_app_b_base_dir=/opt/otel-demo-app2

[all:vars]
ansible_user=singhm
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3

