- name: Prepare base directories (Agents)
  hosts: otel_agents
  become: true
  roles:
    - base
    - docker
    - otel_agent

- name: Prepare base directories (Gateways)
  hosts: otel_gateways
  become: true
  roles:
    - base
    - docker
    - otel-gateway

- name: Deploy OTel Agent
  hosts: otel_agents
  become: true
  roles:
    - otel_agent

- name: Deploy OTel Gateway
  hosts: otel_gateways
  become: true
  roles:
    - otel-gateway

- name: Prepare base directories (Prometheus)
  hosts: prom_agents
  become: true
  roles:
    - base
    - docker
    - prometheus

- name: Deploy Prometheus
  hosts: prom_agents
  become: true
  roles:
    - prometheus

- name: Prepare base directories (Grafana)
  hosts: grafana_agents
  become: true
  roles:
    - base
    - docker
    - grafana

- name: Deploy Grafana
  hosts: grafana_agents
  become: true
  roles:
    - grafana

- name: Prepare base directories (Splunk)
  hosts: splunk_agents
  become: true
  roles:
    - base
    - docker
    - splunk

- name: Deploy Splunk
  hosts: splunk_agents
  become: true
  roles:
    - splunk
