- name: Install Docker
  hosts: docker_host
  become: true
  roles:
    - docker

- name: Deploy Otel-Collector(Directory Creation+File Upload+Docker Startup)
  hosts: otel_agents
  become: true
  roles:
    - base
    - otel_agent

- name: Deploy Otel-Gateway(Directory Creation+File Upload+Docker Startup)
  hosts: otel_gateways
  become: true
  roles:
    - base
    - otel-gateway

#- name: Deploy OTel Agent
#  hosts: otel_agents
#  become: true
#  roles:
#    - otel_agent

#- name: Deploy OTel Gateway
#hosts: otel_gateways
# become: true
#  roles:
#    - otel-gateway

- name: Deploy Prometheus(Directory Creation+File Upload+Docker Startup)
  hosts: prom_agents
  become: true
  roles:
    - base
    - prometheus

#- name: Deploy Prometheus
#  hosts: prom_agents
#  become: true
#  roles:
#    - prometheus

- name: Deploy Grafana(Directory Creation+File Upload+Docker Startup)
  hosts: grafana_agents
  become: true
  roles:
    - base
    - grafana

#- name: Deploy Grafana
#  hosts: grafana_agents
#  become: true
#  roles:
#    - grafana

- name: Deploy Splunk(Directory Creation+File Upload+Docker Startup)
  hosts: splunk_agents
  become: true
  roles:
    - base
    - splunk

#- name: Deploy Splunk
#  hosts: splunk_agents
#  become: true
#  roles:
#    - splunk

- name: Deploy Node-Exporter(Directory Creation+File Upload+Docker Startup)
  hosts: node_exporter_agents
  become: true
  roles:
    - base
    - node-exporter

#- name: Deploy node-exporter
#  hosts: node_exporter_agents
#  become: true
#  roles:
#    - node-exporter

- name: Deploy Exporters(Directory Creation+File Upload+Docker Startup)
  hosts: exporters_agents
  become: true
  roles:
    - base
    - exporters

#- name: Deploy exporters
#  hosts: exporters_agents
#  become: true
#  roles:
#    - exporters

- name: Deploy Demo-App(Directory Creation+File Upload+Docker Startup)
  hosts: otel_demo_app
  become: true
  roles:
    - base
    - otel-demo-app

#- name: Deploy otel-demo-app
#  hosts: otel_demo_app
#  become: true
#  roles:
#    - otel-demo-app

- name: Deploy Demo-App2(Directory Creation+File Upload+Docker Startup)
  hosts: otel_demo_app2
  become: true
  roles:
    - base
    - otel-demo-app2

#- name: Deploy otel-demo-app_b
#  hosts: otel_demo_app2
#  become: true
#  roles:
#    - otel-demo-app2
