- name: Copy otel demo app Dockerfile
  copy:
    src: Dockerfile
    dest: "{{ otel_demo_app_b_base_dir }}/Dockerfile"
    mode: '0644'
- name: Copy otel demo app app_b.py
  copy:
    src: app_b.py
    dest: "{{ otel_demo_app_b_base_dir }}/app_b.py"
    mode: '0644'
- name: Copy docker-compose file
  copy:
    src: docker-compose.yml
    dest: "{{ otel_demo_app_b_base_dir }}/docker-compose.yml"
    mode: '0644'
  notify: 
    - start app agent
